In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Rikitea,PF,-23.1203,-134.9692,74.35,78,100,17.54,overcast clouds,2022-07-17 17:55:42
1,1,Esperance,AU,-33.8667,121.9000,53.26,86,100,10.09,light rain,2022-07-17 17:55:42
2,2,Iqaluit,CA,63.7506,-68.5145,46.13,87,100,9.22,light rain,2022-07-17 17:55:43
3,3,Sembe,CG,1.6481,14.5806,72.21,92,100,1.79,light rain,2022-07-17 17:55:43
4,4,Ushuaia,AR,-54.8000,-68.3000,42.46,52,40,5.75,scattered clouds,2022-07-17 17:55:43

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [6]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Rikitea,PF,-23.1203,-134.9692,74.35,78,100,17.54,overcast clouds,2022-07-17 17:55:42
3,3,Sembe,CG,1.6481,14.5806,72.21,92,100,1.79,light rain,2022-07-17 17:55:43
5,5,Praia Da Vitoria,PT,38.7333,-27.0667,79.05,69,75,12.55,broken clouds,2022-07-17 17:55:44
6,6,Mahebourg,MU,-20.4081,57.7000,70.09,64,40,19.57,scattered clouds,2022-07-17 17:55:44
7,7,Souillac,MU,-20.5167,57.5167,70.18,64,40,19.57,scattered clouds,2022-07-17 17:55:45
9,9,Bambous Virieux,MU,-20.3428,57.7575,70.05,64,40,19.57,scattered clouds,2022-07-17 17:53:09
11,11,Portland,US,45.5234,-122.6762,72.50,55,14,5.99,few clouds,2022-07-17 17:55:45
14,14,Kendari,ID,-3.9450,122.4989,74.14,95,100,2.77,light rain,2022-07-17 17:55:46
19,19,Kavieng,PG,-2.5744,150.7967,81.86,80,71,14.70,light rain,2022-07-17 17:55:48
21,21,Kapaa,US,22.0752,-159.3190,77.47,84,100,5.01,overcast clouds,2022-07-17 17:55:49

In [10]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [13]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Rikitea,PF,-23.1203,-134.9692,74.35,78,100,17.54,overcast clouds,2022-07-17 17:55:42
3,3,Sembe,CG,1.6481,14.5806,72.21,92,100,1.79,light rain,2022-07-17 17:55:43
5,5,Praia Da Vitoria,PT,38.7333,-27.0667,79.05,69,75,12.55,broken clouds,2022-07-17 17:55:44
6,6,Mahebourg,MU,-20.4081,57.7000,70.09,64,40,19.57,scattered clouds,2022-07-17 17:55:44
7,7,Souillac,MU,-20.5167,57.5167,70.18,64,40,19.57,scattered clouds,2022-07-17 17:55:45
...,...,...,...,...,...,...,...,...,...,...,...
714,714,Changde,CN,29.0464,111.6783,78.46,94,94,2.13,overcast clouds,2022-07-17 17:58:58
715,715,Sao Miguel Do Araguaia,BR,-13.2750,-50.1628,95.36,16,25,6.62,scattered clouds,2022-07-17 17:58:18
716,716,Marsabit,KE,2.3284,37.9899,70.00,44,72,23.11,broken clouds,2022-07-17 17:59:27
717,717,Mayfield,US,36.7417,-88.6367,78.91,95,100,0.00,light rain,2022-07-17 17:59:27
718,718,Mincivan,AZ,39.0294,46.7185,83.82,34,0,1.23,clear sky,2022-07-17 17:59:28

In [14]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,74.35,overcast clouds,-23.1203,-134.9692,
3,Sembe,CG,72.21,light rain,1.6481,14.5806,
5,Praia Da Vitoria,PT,79.05,broken clouds,38.7333,-27.0667,
6,Mahebourg,MU,70.09,scattered clouds,-20.4081,57.7000,
7,Souillac,MU,70.18,scattered clouds,-20.5167,57.5167,
9,Bambous Virieux,MU,70.05,scattered clouds,-20.3428,57.7575,
11,Portland,US,72.50,few clouds,45.5234,-122.6762,
14,Kendari,ID,74.14,light rain,-3.9450,122.4989,
19,Kavieng,PG,81.86,light rain,-2.5744,150.7967,
21,Kapaa,US,77.47,overcast clouds,22.0752,-159.3190,

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
radius = 5000

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {
        "location": f"{lat},{lng}",
        "radius": radius,
        "types" : "hotel",
        "key": g_key
    }

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
        
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

Hotel not found... skipping.

In [16]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,74.35,overcast clouds,-23.1203,-134.9692,Rikitea
3,Sembe,CG,72.21,light rain,1.6481,14.5806,Sembe
5,Praia Da Vitoria,PT,79.05,broken clouds,38.7333,-27.0667,Praia da Vitória
6,Mahebourg,MU,70.09,scattered clouds,-20.4081,57.7000,Mahebourg
7,Souillac,MU,70.18,scattered clouds,-20.5167,57.5167,Souillac

In [19]:
# 8a. Create the output File (CSV)
# Create the output file (CSV).
output_data_file = "WeatherPy_Vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [20]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [21]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

In [22]:
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))